version: "3.8"
services:
    node1:
        build:
            context: .            
        environment:
            NODE_PORT: "8080"
        ports:
            - "8080:8080"
        network_mode: host
        command: ["blockchain", "8080"]

    node2:
        build:
            context: .
        depends_on: 
            - node1
        environment:
            NODE_PORT: "8081"
            PEER_PORT: "localhost:8080"
        ports:
            - "8081:8081"
        network_mode: host
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s
        command: sh -c './wait-for localhost:8080 -- blockchain 8081 localhost:8080'
    node3:
        build:
            context: .
        depends_on: 
            - node2
        environment:
            NODE_PORT: "8082"
            PEER_PORT: "localhost:8081"
        ports:
            - "8082:8082"
        network_mode: host
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8081"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s
        command: sh -c './wait-for localhost:8081 -- blockchain 8082 localhost:8081'
